pre_bump_hooks = [
    "cargo test",
    "cargo clippy",
    "cargo build --release",
    "cargo fmt --all",
    "./gen-readme.sh",
    "cargo bump {{version}}",
]


post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
    "cargo package",
    "cargo publish"
]

[changelog]
template = "remote"
remote = "github.com"
repository = "rusty-forkfork"
owner = "oknozor"

authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
    { signature = "Zshoham", username = "Zshoham" },
]
